jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  application:
    name: emojinious-backend
  data:
    redis:
      host: ENC(+wbrYVQvJOCGwJb04tH8kHm1FNZkNNw4Zc0lokyjSddSQHjC6fr24hkZhCeuZQCQwKAV0R2eaSwUzjzmkm3o2DSvxT1Upw/3)
      port: 15733
      password: ENC(dbtRPEzugAJK7jIuKNgFhX097hSLYZsXBhoxlJGMDhaf6IQ+mHdEppU7leiQKM8V)
      ssl:
        enabled: true

jwt:
  secret: ENC(U1iEDPMT18taS96ZUvkQO8XEoJdjftoiSiFgPYEwfUlNP1oNRPK8MtC5WbPhipG4+/Ygoh7CGqx4NXtJcigdNk71liILkPbB0e8oQvWccaE=)
  expiration: 3600000

server:
  port: 8080

logging:
  level:
    root: INFO
    com.emojinious: DEBUG